g.addV('force').property(id, '1').property('name', 'west midlands').next()
g.addV('force').property(id, '2').property('name', 'MET').next()
g.addV('force').property(id, '3').property('name', 'PSNI').next()
g.addV('force').property(id, '4').property('name', 'West Yorkshire').next()
g.addV('force').property(id, '5').property('name', 'Police Scotland').next()
g.addV('force').property(id, '6').property('name', 'Avon and Somerset').next()

g.addV('Software').property(id, '100').property('name', 'Box').next()
g.addV('Software').property(id, '101').property('name', 'Niche').next()
g.addV('Software').property(id, '102').property('name', 'Storm').next()

g.addV('Suppliers').property(id, '300').property('name', 'AWS').next()
g.addV('Suppliers').property(id, '301').property('name', 'Microsoft').next()
g.addV('Suppliers').property(id, '303').property('name', 'Northgate').next()
g.addV('Suppliers').property(id, '304').property('name', 'Steria').next()
g.addV('Suppliers').property(id, '305').property('name', 'SAAB').next()
g.addV('Suppliers').property(id, '306').property('name', 'Niche').next()
g.addV('Suppliers').property(id, '307').property('name', 'Motorola').next()
g.addV('Suppliers').property(id, '308').property('name', 'Altia').next()
g.addV('Suppliers').property(id, '309').property('name', 'Clue').next()
g.addV('Suppliers').property(id, '310').property('name', 'Emronille').next()
g.addV('Suppliers').property(id, '311').property('name', 'Choros').next()

g.addV('SI').property(id, '600').property('name', 'Deloittes').next()
g.addV('SI').property(id, '601').property('name', 'Cap').next()
g.addV('SI').property(id, '602').property('name', 'Atos').next()
g.addV('SI').property(id, '603').property('name', 'Accenture').next()

g.addV('People').property(id, '400').property('firstname', 'Amy').property('lastname', '').next()

g.addV('Programs').property(id, '500').property('name', 'NLEDS').next()
g.addV('Programs').property(id, '501').property('name', 'ESMCP').next()
g.addV('Programs').property(id, '502').property('name', 'HOB').next()
g.addV('Programs').property(id, '503').property('name', 'NEP').next()
g.addV('Programs').property(id, '504').property('name', 'NPTC').next()
g.addV('Programs').property(id, '505').property('name', 'PICTCO').next()
g.addV('Programs').property(id, '506').property('name', 'PTF').next()
g.addV('Programs').property(id, '507').property('name', 'TFWG').next()
g.addV('Programs').property(id, '508').property('name', 'APCC').next()

g.addV('Government').property(id, '700').property('name', 'Home office').next()
g.addV('Government').property(id, '701').property('name', 'GDS').next()
g.addV('Government').property(id, '702').property('name', 'MOJ').next()

g.V('1').addE('engaged').to(g.V('300')).next()
g.V('508').addE('engaged').to(g.V('505')).next()
g.V('508').addE('engaged').to(g.V('506')).next()
g.V('504').addE('engaged').to(g.V('503')).next()
g.V('506').addE('engaged').to(g.V('505')).next()
g.V('507').addE('engaged').to(g.V('504')).next()
g.V('504').addE('engaged').to(g.V('505')).next()
g.V('508').addE('engaged').to(g.V('505')).next()
g.V('508').addE('engaged').to(g.V('506')).next()
g.V('300').addE('engaged').to(g.V('500')).next()
g.V('700').addE('engaged').to(g.V('500')).next()

g.V('701').addE('influencing').to(g.V('700')).next()
g.V('702').addE('influencing').to(g.V('700')).next()
g.V('700').addE('influencing').to(g.V('506')).next()
