g.addV('person').property(id, '1').property('firstname', 'charlie').property('lastname', 'llewellyn').property('phone_number', '07883456286').next()
g.addV('person').property(id, '2').property('firstname', 'wes').property('lastname', 'neary').next()
g.addV('person').property(id, '3').property('firstname', 'charlie').property('lastname', 'anderson').next()
g.addV('person').property(id, '4').property('firstname', 'olivia').property('lastname', 'smith').next()
g.addV('person').property(id, '5').property('firstname', 'ruby').property('lastname', 'jones').property('phone_number', '07543987563').next()
g.addV('person').property(id, '6').property('firstname', 'emily').property('lastname', 'taylor').next()
g.addV('person').property(id, '7').property('firstname', 'grace').property('lastname', 'williams').next()
g.addV('person').property(id, '8').property('firstname', 'jessica').property('lastname', 'brown').next()
g.addV('person').property(id, '9').property('firstname', 'alfie').property('lastname', 'hudson').next()
g.addV('person').property(id, '10').property('firstname', 'charlie').property('lastname', 'gibson').property('phone_number', '07357267351').next()
g.addV('person').property(id, '11').property('firstname', 'daniel').property('lastname', 'mills').next()
g.addV('person').property(id, '12').property('firstname', 'james').property('lastname', 'berry').next()
g.addV('person').property(id, '13').property('firstname', 'william').property('lastname', 'barnes').next()
g.addV('person').property(id, '14').property('firstname', 'samuel').property('lastname', 'pearson').property('phone_number', '07896536287').next()
g.addV('person').property(id, '15').property('firstname', 'george').property('lastname', 'kaur').next()
g.addV('person').property(id, '16').property('firstname', 'joseph').property('lastname', 'booth').next()
g.addV('person').property(id, '17').property('firstname', 'lewis').property('lastname', 'dixon').next()
g.addV('person').property(id, '18').property('firstname', 'ethan').property('lastname', 'grant').next()

g.addV('crime_type').property(id, '1001').property('crime_type', 'Gambling').next()
g.addV('crime_type').property(id, '1002').property('crime_type', 'Intellectual_property_violation').next()
g.addV('crime_type').property(id, '1003').property('crime_type', 'Larceny').next()
g.addV('crime_type').property(id, '1004').property('crime_type', 'Payola').next()
g.addV('crime_type').property(id, '1005').property('crime_type', 'Pickpocketing').next()
g.addV('crime_type').property(id, '1006').property('crime_type', 'Possessing_stolen_property').next()
g.addV('crime_type').property(id, '1007').property('crime_type', 'Robbery').next()
g.addV('crime_type').property(id, '1008').property('crime_type', 'Smuggling').next()
g.addV('crime_type').property(id, '1009').property('crime_type', 'Tax_evasion').next()
g.addV('crime_type').property(id, '1010').property('crime_type', 'Theft').next()

g.addV('phone_record').property(id, '10000').property('phone_number', '07543987563').next()
g.addV('phone_record').property(id, '10001').property('phone_number', '07645378726').next()
g.addV('phone_record').property(id, '10002').property('phone_number', '07883456286').next()

g.addV('location').property(id, '100000').property('location_name', 'Bellagio Las Vegas').next()

g.addV('phone_images').property(id, '1000000').property('file_location', 's3://case-id/suspect-id/phone-images/file1.jpg').next()
g.addV('phone_images').property(id, '1000001').property('file_location', 's3://case-id/suspect-id/phone-images/file2.jpg').next()

g.addV('CCTV').property(id, '10000000').property('location', 'Bellagio Las Vegas').next()

g.V('1').addE('phone_records').to(g.V('10000')).next()
g.V('10000').addE('phone_call').to(g.V('5')).next()
g.V('5').addE('phone_records').to(g.V('10002')).next()
g.V('10002').addE('phone_call').to(g.V('1')).next()
g.V('2').addE('phone_records').to(g.V('10001')).next()

g.V('1').addE('phone_image').to(g.V('1000000')).next()
g.V('1').addE('phone_image').to(g.V('1000001')).next()
g.V('100000').addE('location').to(g.V('1000000')).next()

g.V('1000001').addE('facial_match').to(g.V('10000000')).next()
g.V('10000000').addE('location').to(g.V('100000')).next()

g.V('5').addE('facial_match').to(g.V('10000000')).next()
