AWSTemplateFormatVersion: 2010-09-09

Resources:

  CodePipelineBucket:
    Type: AWS::S3::Bucket

  CodeCommitRepo:
    Type: "AWS::CodeCommit::Repository"
    Properties: 
      RepositoryDescription: CodeCommit Demo
      RepositoryName: code-commit-demo

  CloudFormationRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service: cloudformation.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      Path: /
      RoleName: cjl-fluff-Cloudformation

  CodepipelineServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      RoleName: cjl-fluff-Pipeline-Service-Role

  CodepipelineRolePolicies:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "cjl-fluff-Service-Policy"
      PolicyDocument:
        Statement:
        - Action:
          - s3:GetObject
          - s3:GetObjectVersion
          - s3:GetBucketVersioning
          Resource: "*"
          Effect: Allow
        - Action:
          - s3:PutObject
          Resource:
          - arn:aws:s3:::codepipeline*
          - arn:aws:s3:::elasticbeanstalk*
          Effect: Allow
        - Action:
          - codecommit:CancelUploadArchive
          - codecommit:GetBranch
          - codecommit:GetCommit
          - codecommit:GetUploadArchiveStatus
          - codecommit:UploadArchive
          Resource: "*"
          Effect: Allow
        - Action:
          - codedeploy:CreateDeployment
          - codedeploy:GetApplicationRevision
          - codedeploy:GetDeployment
          - codedeploy:GetDeploymentConfig
          - codedeploy:RegisterApplicationRevision
          Resource: "*"
          Effect: Allow
        - Action:
          - elasticbeanstalk:*
          - ec2:*
          - elasticloadbalancing:*
          - autoscaling:*
          - cloudwatch:*
          - s3:*
          - sns:*
          - cloudformation:*
          - rds:*
          - sqs:*
          - ecs:*
          - iam:PassRole
          Resource: "*"
          Effect: Allow
        - Action:
          - lambda:InvokeFunction
          - lambda:ListFunctions
          Resource: "*"
          Effect: Allow
        - Action:
          - opsworks:CreateDeployment
          - opsworks:DescribeApps
          - opsworks:DescribeCommands
          - opsworks:DescribeDeployments
          - opsworks:DescribeInstances
          - opsworks:DescribeStacks
          - opsworks:UpdateApp
          - opsworks:UpdateStack
          Resource: "*"
          Effect: Allow
        - Action:
          - cloudformation:CreateStack
          - cloudformation:DeleteStack
          - cloudformation:DescribeStacks
          - cloudformation:UpdateStack
          - cloudformation:CreateChangeSet
          - cloudformation:DeleteChangeSet
          - cloudformation:DescribeChangeSet
          - cloudformation:ExecuteChangeSet
          - cloudformation:SetStackPolicy
          - cloudformation:ValidateTemplate
          - iam:PassRole
          Resource: "*"
          Effect: Allow
        - Action:
          - codebuild:BatchGetBuilds
          - codebuild:StartBuild
          Resource: "*"
          Effect: Allow
        Version: '2012-10-17'
      Roles: 
        - 
          Ref: "CodepipelineServiceRole"

  CloudFormationRolePolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "cjl-fluff-Cloudformation-Policy"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Action:
            - s3:GetObject
            - s3:GetObjectVersion
            - s3:GetBucketVersioning
            Resource: "*"
            Effect: Allow
          - Action:
            - s3:PutObject
            Resource:
            - arn:aws:s3:::codepipeline*
            Effect: Allow
          - Action:
            - lambda:*
            Resource:
            - !Join [ '', [ 'arn:aws:lambda:', !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ':function:*' ] ]
            Effect: Allow
          - Action:
            - apigateway:*
            Resource:
            - !Join [ '', [ 'arn:aws:apigateway:', !Ref "AWS::Region", '::*' ] ]
            Effect: Allow
          - Action:
            - iam:GetRole
            - iam:CreateRole
            - iam:DeleteRole
            - iam:PutRolePolicy
            Resource:
            - !Join [ '', [ 'arn:aws:iam::', !Ref "AWS::AccountId", ':role/*' ] ]
            Effect: Allow
          - Action:
            - iam:AttachRolePolicy
            - iam:DeleteRolePolicy
            - iam:DetachRolePolicy
            Resource:
            - !Join [ '', [ 'arn:aws:iam::', !Ref "AWS::AccountId", ':role/*' ] ]
            Effect: Allow
          - Action:
            - iam:PassRole
            Resource:
            - "*"
            Effect: Allow
          - Action:
            - cloudformation:CreateChangeSet
            Resource:
            - !Join [ '', [ 'arn:aws:cloudformation:', !Ref "AWS::Region", ':aws:transform/Serverless-2016-10-31' ] ]
            Effect: Allow
          - Action:
            - codedeploy:CreateApplication
            - codedeploy:DeleteApplication
            - codedeploy:RegisterApplicationRevision
            Resource:
            - !Join [ '', [ 'arn:aws:codedeploy:', !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ':application:*' ] ]
            Effect: Allow
          - Action:
            - codedeploy:CreateDeploymentGroup
            - codedeploy:CreateDeployment
            - codedeploy:GetDeployment
            Resource:
            - !Join [ '', [ 'arn:aws:codedeploy:', !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ':deploymentgroup:*' ] ]
            Effect: Allow
          - Action:
            - codedeploy:GetDeploymentConfig
            Resource:
            - !Join [ '', [ 'arn:aws:codedeploy:', !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ':deploymentconfig:*' ] ]
            Effect: Allow
      Roles: 
        - 
          Ref: "CloudFormationRole"

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole: !Ref CodeBuildRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/python:3.3.6
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 10

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cjl-fluff-Codebuild-Role
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'logs:*'
                - 'ec2:CreateNetworkInterface'
                - 'ec2:DescribeNetworkInterfaces'
                - 'ec2:DeleteNetworkInterface'
                - 'ec2:DescribeSubnets'
                - 'ec2:DescribeSecurityGroups'
                - 'ec2:DescribeDhcpOptions'
                - 'ec2:DescribeVpcs'
                - 'ec2:CreateNetworkInterfacePermission'
                Effect: Allow
                Resource: '*'
                #- Action: s3:PutObject
                #Effect: Allow
                #Resource: arn:aws:s3:::*/*
              - Effect: Allow
                Resource:
                - arn:aws:logs:eu-west-1:008369042577:log-group:/aws/codebuild/code-build-demo
                - arn:aws:logs:eu-west-1:008369042577:log-group:/aws/codebuild/code-build-demo:*
                Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              - Effect: Allow
                Resource:
                - arn:aws:s3:::codepipeline-eu-west-1-*
                Action:
                - s3:PutObject
                - s3:GetObject
                - s3:GetObjectVersion
              - Effect: Allow
                Resource:
                - arn:aws:logs:eu-west-2:008369042577:log-group:/aws/codebuild/test
                - arn:aws:logs:eu-west-2:008369042577:log-group:/aws/codebuild/test:*
                Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              - Effect: Allow
                Resource:
                - arn:aws:s3:::codepipeline-eu-west-2-*
                Action:
                - s3:PutObject
                - s3:GetObject
                - s3:GetObjectVersion
              - Effect: Allow
                Action:
                - ssm:GetParameters
                Resource: arn:aws:ssm:eu-west-2:008369042577:parameter/CodeBuild/*

  CloudWatchEventRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cloudWatch-CodeCommitEvent-Role
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [events.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - codepipeline:StartPipelineExecution
              Resource:
                - !Join [ '', [ 'arn:aws:codepipeline:', !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ':', !Ref CodePipeline ] ]

          
  CodePipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: cjl-fluff
      RestartExecutionOnUpdate: true
      RoleArn: !GetAtt CodepipelineServiceRole.Arn
      ArtifactStore: 
        Type: S3
        Location: !Ref CodePipelineBucket
      Stages:
        - 
          Name: Source
          Actions: 
            - 
              Name: SourceAction
              ActionTypeId: 
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              Configuration: 
                BranchName: master
                PollForSourceChanges: 'false'
                RepositoryName: code-commit-demo
              OutputArtifacts: 
                - 
                  Name: MyApp
              RunOrder: 1
        - 
          Name: Build
          Actions: 
            - 
              Name: CodeBuild
              InputArtifacts: 
                - 
                  Name: MyApp
              Configuration: 
                ProjectName: !Ref CodeBuildProject
              ActionTypeId: 
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              OutputArtifacts: 
                - 
                  Name: MyAppBuild
              RunOrder: 1
        - 
          Name: Staging
          Actions:
            - 
              Name: codedeploy-demo
              InputArtifacts:
                - 
                  Name: MyAppBuild
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                Capabilities: CAPABILITY_NAMED_IAM
                ChangeSetName: codedeploy-demo-changeset
                RoleArn: !GetAtt CloudFormationRole.Arn
                StackName: codedeploy-demo
                TemplatePath: MyAppBuild::outputSamTemplate.yaml
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              OutputArtifacts: []
              RunOrder: 1
        - 
          Name: Execture-change-set
          Actions:
            - 
              Name: codedeploy-demo-changeset
              InputArtifacts: []
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: codedeploy-demo-changeset
                StackName: codedeploy-demo
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              OutputArtifacts: []
              RunOrder: 1

  EventRule: 
    Type: "AWS::Events::Rule"
    Properties: 
      Description: "EventRule for codepipeline"
      EventPattern: 
        source:
        - aws.codecommit
        detail-type:
        - CodeCommit Repository State Change
        resources:
        - !GetAtt CodeCommitRepo.Arn
        detail:
          event:
          - referenceCreated
          - referenceUpdated
          referenceType:
          - branch
          referenceName:
          - master
      State: "ENABLED"
      Targets: 
        - Arn: !Join [ '', [ 'arn:aws:codepipeline:', !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ':', !Ref CodePipeline ] ]
          Id: "TargetFunctionV1"
          RoleArn: !GetAtt CloudWatchEventRole.Arn

