codeCommitBucket='codepipeline-demo-codepipelinebucket-17uyrwpx0ypb5'

echo "
version: 0.1
phases:
  install:
    commands:
      - npm install time
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket $codeCommitBucket
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml" > buildSpec.yaml
