AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
   
  InputBucket:
    Type: AWS::S3::Bucket

  OutputBucket:
    Type: AWS::S3::Bucket

  callStepFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./lex
      #Policies:
      #- AWSStepFunctionsFullAccess
        #      Events:
        #        MyTimeApi:
        #          Type: S3
        #          Properties:
        #            Bucket: !Ref InputBucket
        #            Events: s3:ObjectCreated:*
      Timeout: 300
      #AutoPublishAlias: live

      #Outputs:
      #  InputBucket:
      #    Description: The bucket where objects are uploaded to trigger the data pipepline
      #    Value: !Ref InputBucket
