AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
   
  InputBucket:
    Type: AWS::S3::Bucket

  callStepFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: callStepFunction.lambda_handler
      Runtime: python3.6
      CodeUri: ./callStepFunction
      Policies:
      - AmazonS3FullAccess
      - AWSStepFunctionsFullAccess
      Events:
        MyTimeApi:
          Type: S3
          Properties:
            Bucket: !Ref InputBucket
            Events: s3:ObjectCreated:*
      Timeout: 60

  dataType:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dataType.lambda_handler
      Runtime: python3.6
      CodeUri: ./dataType
      Policies: 
      - AmazonS3FullAccess
      Environment:
        Variables:
          S3_ENDPOINT: ''
      Timeout: 60

  comprehendFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: comprehend.lambda_handler
      Runtime: python3.6
      CodeUri: ./comprehend
      Policies:
      - AmazonS3FullAccess
      - ComprehendFullAccess
      Timeout: 60

  rekognitionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: rekognition.lambda_handler
      Runtime: python3.6
      CodeUri: ./rekognition
      Policies:
      - AmazonS3FullAccess
      - AmazonRekognitionFullAccess
      Timeout: 60
           
  DefaultFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: catchall.lambda_handler
      Runtime: python3.6
      CodeUri: ./catchall
      Timeout: 60

  StepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Demo-stepFunction-Role
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
                  Service: !Join [ '', [ 'states.', !Ref "AWS::Region", '.amazonaws.com' ] ]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - lambda:InvokeFunction
              Resource: "*"

  StepFunction:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      StateMachineName: Demo-state-machine
      DefinitionString: 
        Fn::Sub:
          - |
            {
              "Comment": "An example for the chelt hack day",
              "StartAt": "Identify",
              "States": {
                "Identify": {
                  "Type": "Task",
                  "Resource": "${dataType}",
                  "ResultPath": "$",
                  "Next": "RouteDataType"
                },
              "RouteDataType": {
              "Type" : "Choice",
              "Choices": [{
                "Variable": "$[0].dataType",
                "StringEquals": "image/jpeg",
                "Next": "runRekognition"
              },{
                "Variable": "$[0].dataType",
                "StringEquals": "text/plain",
                "Next": "runComprehend"
              }],
              "Default": "inconclusiveDataType"
            },
                "runRekognition": {
                  "Type": "Task",
                  "Resource": "${rekognition}",
                  "End": true
                },    
                "runComprehend": {
                  "Type": "Task",
                  "Resource": "${comprehend}",
                  "End": true
                },
                "inconclusiveDataType": {
                  "Type": "Task",
                  "Resource": "${default}",
                  "End": true
                }
              }
            }
          - { dataType: !GetAtt dataType.Arn, default: !GetAtt DefaultFunction.Arn, comprehend: comprehendFunction.Arn, rekognition: rekognitionFunction.Arn }
      RoleArn: !GetAtt StepFunctionRole.Arn

Outputs:
  InputBucket:
    Description: The bucket where objects are uploaded to trigger the data pipepline
    Value: !Ref InputBucket
